name: Branch Policy

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  validate-branch-flow:
    runs-on: ubuntu-latest

    steps:
      - name: Validate branch flow
        run: |
          SOURCE="${{ github.head_ref }}"
          TARGET="${{ github.base_ref }}"

          echo "Source branch: $SOURCE"
          echo "Target branch: $TARGET"

          if [ "$TARGET" = "dev" ] && [ "$SOURCE" != "local" ]; then
            echo "❌ Only local can create a PR to dev."
            exit 1
          fi

          if [ "$TARGET" = "production" ] && [ "$SOURCE" != "dev" ]; then
            echo "❌ Only dev can create a PR to production."
            exit 1
          fi

          echo "✅ Branch flow is valid."